### ISSUE TITLE
Doesn't compile (xlocale.h)

### ISSUE THREAD

**Issue by mleduque** [couchbase/couchbase-lite-core#897]
cargo build fails with
```
--- stderr
Found ICU libs at /usr/lib/x86_64-linux-gnu/libicuuc.so;/usr/lib/x86_64-linux-gnu/libicui18n.so;/usr/lib/x86_64-linux-gnu/libicudata.so
Using libicu header files in /usr/include
Found libz at /usr/lib/x86_64-linux-gnu/libz.so
Using libz header files in /usr/include
Can't open perl script "/home/mick/dev/couchbase-lite-rust/couchbase-lite-core-sys/couchbase-lite-core/scripts/config.pl": Aucun fichier ou dossier de ce type
/home/mick/dev/couchbase-lite-rust/couchbase-lite-core-sys/couchbase-lite-core/vendor/BLIP-Cpp/src/websocket/WebSocketImpl.cc: In member function ‘void litecore::websocket::WebSocketImpl::timedOut()’:
/home/mick/dev/couchbase-lite-rust/couchbase-lite-core-sys/couchbase-lite-core/vendor/BLIP-Cpp/src/websocket/WebSocketImpl.cc:347:49: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘std::chrono::duration<long int>::rep’ {aka ‘long int’} [-Wformat=]
  347 |         logError("No response received after %lld sec -- disconnecting", _curTimeout.count());
      |                                              ~~~^                        ~~~~~~~~~~~~~~~~~~~
      |                                                 |                                         |
      |                                                 long long int                             std::chrono::duration<long int>::rep {aka long int}
      |                                              %ld
/home/mick/dev/couchbase-lite-rust/couchbase-lite-core-sys/couchbase-lite-core/vendor/fleece/Fleece/Support/NumConversion.cc:24:10: fatal error: xlocale.h: Aucun fichier ou dossier de ce type
   24 | #include <xlocale.h>
      |          ^~~~~~~~~~~
compilation terminated.
```

This is probably the same problem that is fixed in https://github.com/couchbaselabs/fleece/commit/cf4ca9fd03d42b03280504027147786d7ed9ec3c ?

**Comment by borrrden** [comment]
Yes it is the same issue.  In the long run hopefully I can simply remove that header.  It's not as big of an issue here because we build with glibc 2.17.

**Comment by Dushistov** [comment]
As I mentioned [here](https://github.com/couchbaselabs/fleece/pull/57#issuecomment-536763500) it is safe removing of `#include <xlocale.h>` even with old glibc, but looks like master is not the main branch? I made PR against fleece master, but looks like coucbase-lite-core uses completely different branch with completely different commits.

**Comment by borrrden** [comment]
It does, but I fast forwarded master today on Fleece in order to get ready to move back to master again (there was a dev branch with lots of changes and I needed to get it under control first)

**Comment by borrrden** [comment]
master branch should be all good with this now.
