### ISSUE TITLE
Build target CppTests fails to compile on macOS

### ISSUE THREAD

**Issue by mz2** [couchbase/couchbase-lite-core#276]
Build target CppTests fails to compile on macOS (10.12.6) for current head of master (e1c3fdbe8a37c3ff3b671acffc0f3b9fddb02f2e) when building with `./build_cmake/scripts/build_macos.sh`:

```
/Users/mz2/Projects/couchbase-lite-core/tools/cblite/cbliteTool+query.cc:67:41: error: no member named 'docID' in 'C4QueryEnumerator'
            cout << "\"_id\": \"" << e->docID << "\"";
```

**Comment by mz2** [comment]
Same issue when trying to compile cblite_tool. A recent API change perhaps?

**Comment by snej** [comment]
Sorry, I briefly broke the build with an API change. Fixed in commit bf4fa5035008852517a2a5397302fcb592639c7e.
